# data directory where to store all synchronized log files
datadir: /var/log/shaftlog-server

# port to listen for connections
listen_port: 10661

# address to bind to for connections
bind_address: 0.0.0.0
