# data directory where to hard link new log files
# NOTE: must be on the same filesystem as all log files
datadir: /var/log/shaftlog-client

# how often to scan for new log files in milliseconds
scan_interval: 30000

# list of paths to search for new log files
scan_paths:
- name: syslog
  pattern: /var/log/syslog{,.1}
- name: user
  pattern: /var/log/user.log{,.1}
- name: auth
  pattern: /var/log/auth.log{,.1}

# destinations to sync log files to
# NOTE: urls must end in slash and may contain the following substitutions
#   {hostname}: value returned by gethostname(2)
#   {machine}:  UUID identifier for machine (/etc/machine-id or /var/lib/dbus/machine-id) 
destinations:
- url: http://log1.my.domain.invalid:10655/{hostname}/
- url: http://log2.my.domain.invalid:10655/{hostname}/
