# data directory where to hard link new log files
# NOTE: must be on the same filesystem as all log files
datadir: /var/log/shaftlog-client

# log file to use for logs about synchronization
logfile: /var/log/shaftlog-client.log

# how often to scan for new log files in milliseconds
scan_interval: 30000

# list of paths to search for new log files
scan_paths:
- name: messages
  pattern: /var/log/messages{,.+([0-9])!(.gz)}
- name: cron
  pattern: /var/log/cron{,.+([0-9])!(.gz)}
- name: maillog
  pattern: /var/log/maillog{,.+([0-9])!(.gz)}
- name: secure
  pattern: /var/log/secure{,.+([0-9])!(.gz)}
- name: yum
  pattern: /var/log/yum.log{,.+([0-9])!(.gz)}
- name: audit
  pattern: /var/log/audit/audit.log{,.+([0-9])!(.gz)}
- name: dmesg
  pattern: /var/log/dmesg{,.+([0-9])!(.gz)}
- name: cloudinit
  pattern: /var/log/cloud-init.log{,.+([0-9])!(.gz)}
- name: shaftlog-client
  pattern: /var/log/shaftlog-client.log{,.+([0-9])!(.gz)}
- name: shaftlog-server
  pattern: /var/log/shaftlog-server.log{,.+([0-9])!(.gz)}

# destinations to sync log files to
# NOTE: urls must end in slash and may contain the following substitutions
#   {hostname}: value returned by gethostname(2)
#   {machine}:  UUID identifier for machine (/etc/machine-id or /var/lib/dbus/machine-id) 
destinations:
- url: http://log1.my.domain.invalid:10655/{hostname}/
- url: http://log2.my.domain.invalid:10655/{hostname}/
