# data directory where to hard link new log files
# NOTE: must be on the same filesystem as all log files
datadir: /var/log/shaftlog-client

# log file to use for logs about synchronization
logfile: /var/log/shaftlog-client.log

# how often to scan for new log files in milliseconds
scan_interval: 30000

# how often to print status information
status_interval: 300000

# how often to re-stat one file in round robin to catch missed changes
periodic_trigger_interval: 1000

# list of paths to search for new log files
# NOTE:
# - destination filename is specified by "rename" key
# - filenames may contain the following substitutions:
#   {name}:  pattern name in this configuration file
#   {time}:  time of file detection in milliseconds
#   {atime}: time of last access in milliseconds
#   {mtime}: time of last modification in milliseconds
#   {ctime}: time of last (inode) change in milliseconds
#   {ino}:   inode number
#   {dev}:   device number
# - default rename pattern: "{name}.{mtime}"
# - regex substitution on filename can be specified by "regex_from"
#   and "regex_to"
# - exclude may be used to specify a glob expression of files to
#   exclude from matching files
scan_paths:
- name: messages
  pattern: /var/log/messages*
  exclude: "*.{gz,bz2,xz}"
- name: cron
  pattern: /var/log/cron*
  exclude: "*.{gz,bz2,xz}"
- name: maillog
  pattern: /var/log/maillog*
  exclude: "*.{gz,bz2,xz}"
- name: secure
  pattern: /var/log/secure*
  exclude: "*.{gz,bz2,xz}"
- name: yum
  pattern: /var/log/yum.log*
  exclude: "*.{gz,bz2,xz}"
- name: audit
  pattern: /var/log/audit/audit.log*
  exclude: "*.{gz,bz2,xz}"
- name: dmesg
  pattern: /var/log/dmesg*
  exclude: "*.{gz,bz2,xz}"
- name: cloudinit
  pattern: /var/log/cloud-init.log*
  exclude: "*.{gz,bz2,xz}"
- name: shaftlog-client
  pattern: /var/log/shaftlog-client.log*
  exclude: "*.{gz,bz2,xz}"
- name: shaftlog-server
  pattern: /var/log/shaftlog-server.log*
  exclude: "*.{gz,bz2,xz}"
- name: sudo-io
  pattern: /var/log/sudo-io/**/{log,stderr,stdin,stdout,timing,ttyin,ttyout}
  regex_from: "^/var/log/sudo-io/(.*)"
  regex_to: "sudo-io/$1"

# destinations to sync log files to
# NOTE: urls must end in slash and may contain the following substitutions
#   {hostname}: value returned by gethostname(2)
#   {machine}:  UUID identifier for machine (/etc/machine-id or /var/lib/dbus/machine-id) 
destinations:
- url: http://log1.my.domain.invalid:10655/{hostname}/
- url: http://log2.my.domain.invalid:10655/{hostname}/
